// Escapes raw control characters (newline, tab, carriage return, etc.)
// that appear INSIDE JSON string values, without touching structural
// whitespace outside strings (which JSON.parse already handles fine).
//
// Why this exists: the model is instructed to escape newlines as \n inside
// string values, but sometimes emits a literal newline byte instead. The
// old code replaced ALL control chars anywhere in the payload with a
// single space, which silently collapsed multi-line corrected code and
// bullet-point root causes into one squished line. This version only
// fixes what's actually invalid (control bytes inside strings) and
// preserves everything else.
function sanitizeControlCharsInStrings(text) {
    let result = "";
    let inString = false;
    let isEscaped = false;

    for (let i = 0; i < text.length; i++) {
        const char = text[i];
        const code = text.charCodeAt(i);

        if (inString && isEscaped) {
            // Previous char was a backslash; this char is already an
            // intentional escape sequence (\n, \", \\, etc.) — pass through.
            result += char;
            isEscaped = false;
            continue;
        }

        if (char === "\\" && inString) {
            result += char;
            isEscaped = true;
            continue;
        }

        if (char === '"') {
            inString = !inString;
            result += char;
            continue;
        }

        if (inString && code >= 0x00 && code <= 0x1f) {
            // Raw control character inside a string literal — escape it
            // properly instead of stripping/replacing with a space.
            if (char === "\n") result += "\\n";
            else if (char === "\r") result += "\\r";
            else if (char === "\t") result += "\\t";
            else result += "\\u" + code.toString(16).padStart(4, "0");
            continue;
        }

        result += char;
    }

    return result;
}

function parseAIResponse(aiText) {

    try {

        // Handle AI service failure
        if (typeof aiText !== "string") {

            return {
                bugPattern: "Unknown",
                rootCause:
                    aiText?.error ||
                    aiText?.message ||
                    "AI service unavailable",

                flashcards: [],
                steps: [],
                fix: "",
                correctedCode: "",
                flowchart: [],
                quiz: [],
                learningOutcome: "",
                parsingError: true
            };
        }


        let cleaned = aiText.trim();


        // Remove markdown fences
        cleaned = cleaned
            .replace(/```json/gi, "")
            .replace(/```/g, "")
            .trim();


        // Extract JSON object only
        const start = cleaned.indexOf("{");
        const end = cleaned.lastIndexOf("}");

        if (start !== -1 && end !== -1) {
            cleaned = cleaned.substring(start, end + 1);
        }


        // Fix: only escape control chars found INSIDE string values.
        // (Previously this blanket-replaced every control char anywhere
        // in the payload with a space, which mangled multi-line code and
        // bullet-formatted text whenever the model forgot to escape a
        // newline itself.)
        cleaned = sanitizeControlCharsInStrings(cleaned);


        const parsed = JSON.parse(cleaned);


        return {

            bugPattern:
                parsed.bugPattern || "Unknown",

            rootCause:
                parsed.rootCause ||
                "No root cause explanation returned.",

            flashcards:
                Array.isArray(parsed.flashcards)
                    ? parsed.flashcards
                    : [],

            // Fix: this field is generated by the model per the prompt
            // schema but was silently dropped here — it never reached the
            // frontend.
            steps:
                Array.isArray(parsed.steps)
                    ? parsed.steps
                    : [],

            fix:
                parsed.fix || "",

            correctedCode:
                parsed.correctedCode || "",

            flowchart:
                Array.isArray(parsed.flowchart)
                    ? parsed.flowchart
                    : [],

            quiz:
                Array.isArray(parsed.quiz)
                    ? parsed.quiz
                    : [],

            learningOutcome:
                parsed.learningOutcome || ""

        };


    } catch(error) {

        console.error(
            "JSON Parse Error:",
            error.message
        );


        console.log(
            "FAILED AI RESPONSE:"
        );

        console.log(aiText);


        return {

            bugPattern: "Unknown",

            rootCause:
                "The AI response could not be processed.",

            flashcards: [],

            steps: [],

            fix:
                "Please retry the analysis.",

            correctedCode: "",

            flowchart: [],

            quiz: [],

            learningOutcome:
                "The debugging explanation could not be generated.",

            parsingError:true
        };
    }

}


module.exports = {
    parseAIResponse
};